### ISSUE TITLE
TRANSFER THE CONVERSATION WITH BOT TO THE AGENT

### ISSUE THREAD

**Issue by sayyednazeer** [ankitbko/human-handoff-bot#1]
@ankitbko 
How can i transfer the conversation which i have done with bot to the agent when i get connected with agent.

**Comment by ankitbko** [comment]
I can think of couple of ways to do it. In any case you will need to store the conversation somewhere. Once you have stored conversation, you can display it to the agent. There is no in-built feature in webchat for this. You could try one of the following approach - 
- *Display history side by side (Easy way)* - Instead of displaying conversation history in the chat window, display it in a div beside it. In this way you wont have to change source code of web chat. When agent-user is connected, you can fetch the conversation history of the user using ajax call and just display it (in formatted way) in a div beside the chat window.

- *Display history in web chat (Hard way)* - This is not easy. As I mentioned, this feature is not inbuilt. You will need to modify the web chat source code to fetch the existing conversation from your store and render it. (Or maybe click on a button, fetch it and send it to the web chat). In any case the code needs to be modified to achieve this. Check out the source code here - https://github.com/Microsoft/BotFramework-WebChat

**Comment by ankitbko** [comment]
Closing this issue.
