### ISSUE TITLE
take control of conversation

### ISSUE THREAD

**Issue by jorgelg** [ankitbko/human-handoff-bot#6]
@ankitbko 
Hi! Thanks for the well explained guide!
I've got one question, is it possible to make the agent the one that triggers messages routing with the user instead of the user being the one that asks to talk with an agent?

**Comment by ankitbko** [comment]
Hey.
It is possible. To do any kind of agent-user chatting all you need is *user address* and *agent address* and map them to each other. For agent to initiate the message, he must know the user's address. The only prerequisite to this is that user must have chatted with bot at least once, so that you can save the user's address. The core concept of message routing remains same i.e. agent-user address mapping.

How I envision this is that, in agent's dashboard you can display list of users. Agent can click on any user and start the conversation.

Let me know if this works out for you.

**Comment by jorgelg** [comment]
Cool! thanks! I was thinking about the same, gonna try it out and I'll keep you updated
> How I envision this is that, in agent's dashboard you can display list of users. Agent can click on any user and start the conversation.
